name: Build all

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Berlin # timezone
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-checkout@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
      - if: ${{ hashFiles('./package.json')!=null }}
        id: node
        uses: it-at-m/lhm_actions/action-templates/actions/action-npm-build@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          app-path: ""
      - if: ${{ hashFiles('./pom.xml')!=null }}
        id: maven
        uses: it-at-m/lhm_actions/action-templates/actions/action-maven-build@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0
        with:
          app-path: ""
